---
# tasks file for dovecot

- name: Include the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install RedHat specific packages
  yum: name={{ item }} state=latest
  with_items: dovecot_packages
  when: ansible_os_family == 'RedHat'

- name: Write Dovecot configuration template
  template: >
    src=dovecot-conf.j2
    dest={{ dovecot_config_dir }}/dovecot.conf
    mode=0644 owner=root group=root
    backup=yes
  notify:
    - restart dovecot